In [1]:
text = 'You say goodbye and I say hello.'
text = text.lower()
text = text.replace('.',' .')
print(text)
words = text.split(' ')
print(words)

you say goodbye and i say hello .
['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']


In [2]:
word_to_id = {}
id_to_word = {}
for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word
print(word_to_id)
print(id_to_word)

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


単語リスト'text'を単語IDのリストcorpusに変換

In [ ]:
import numpy as np
corpus = [word_to_id[w] for w in words]
corpus =np.array(corpus)
print(corpus)

for n in corpus:
    print(id_to_word[n])

[0 1 2 3 4 1 5 6]
you
say
goodbye
and
i
say
hello
.


In [10]:
from common.utils import preprocess

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)

[0 1 2 3 4 1 5 6]


In [11]:
import sys
sys.path.append('..')
import numpy as np
from common.utils import preprocess
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(id_to_word)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


共起行列を手で打ち込んでみる．

In [15]:
C = np.array([
    [0,1,0,0,0,0,0],#you
    [1,0,1,0,1,1,0],#say
    [0,1,0,1,0,0,0],#goodbye
    [0,0,1,0,1,0,0],#and
    [0,1,0,1,0,0,0],#i
    [0,1,0,0,0,0,1],#hello
    [0,0,0,0,0,1,0],#.
])
#you say goodbye and i (say) hello .

print(C[0])#youを表現するベクトル


[0 1 0 0 0 0 0]
